VERSION="2.0.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
SIGNING_KEY="GAEOKX5WDJQYCHEDLPH64NTPKDA2B3KOHZIDLM77TQAMEYMTXU4FVEMX"
ACCOUNTS=["GAEOKX5WDJQYCHEDLPH64NTPKDA2B3KOHZIDLM77TQAMEYMTXU4FVEMX"]

[DOCUMENTATION]
ORG_NAME="PayOnProof"
ORG_URL="payonprooftest.vercel.app"
ORG_DESCRIPTION="Multi-anchor routing for cross-border SME payments on Stellar."
  