"use client";

import React from "react";

import type { Transaction } from "@/lib/mock-data";
import Image from "next/image";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import {
  CheckCircle2,
  Copy,
  Download,
  Share2,
  ArrowRight,
  ExternalLink,
} from "lucide-react";
import { useState, useCallback, useRef } from "react";
import { cn } from "@/lib/utils";

interface ProofOfPaymentProps {
  transaction: Transaction;
  onNewTransfer: () => void;
}

export function ProofOfPaymentView({
  transaction,
  onNewTransfer,
}: ProofOfPaymentProps) {
  const [copied, setCopied] = useState<string | null>(null);
  const popRef = useRef<HTMLDivElement>(null);
  const pop = transaction.proofOfPayment;

  const copyToClipboard = useCallback(
    async (text: string, label: string) => {
      await navigator.clipboard.writeText(text);
      setCopied(label);
      setTimeout(() => setCopied(null), 2000);
    },
    []
  );

  const handleDownload = useCallback(() => {
    if (!pop) return;
    const content = `
PROOF OF PAYMENT - POP
========================
Transaction ID: ${transaction.id}
Date: ${new Date(pop.timestamp).toLocaleString()}
Status: VERIFIED

TRANSFER DETAILS
-----------------
Sender: ${pop.sender}
Receiver: ${pop.receiver}
Origin: ${pop.originAmount.toLocaleString()} ${pop.originCurrency}
Received: ${pop.destinationAmount.toLocaleString()} ${pop.destinationCurrency}
Exchange Rate: 1 ${pop.originCurrency} = ${pop.exchangeRate} ${pop.destinationCurrency}
Total Fees: ${pop.totalFees.toFixed(2)} ${pop.originCurrency}
Route: ${pop.route}

BLOCKCHAIN VERIFICATION
------------------------
Stellar TX Hash: ${pop.stellarTxHash}
Network: Stellar Public

This proof of payment was generated by POP (Pay On Proof).
Verify on Stellar: https://stellar.expert/explorer/public/tx/${pop.stellarTxHash}
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `POP-${transaction.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [pop, transaction.id]);

  if (!pop) return null;

  return (
    <div className="flex flex-col gap-6 animate-fade-in-up">
      {/* Success banner */}
      <div className="flex items-center gap-3 rounded-2xl border border-success/20 bg-success/5 p-4">
        <CheckCircle2 className="h-6 w-6 shrink-0 text-success" />
        <div>
          <p className="font-bold text-foreground">Payment Verified</p>
          <p className="text-sm text-muted-foreground">
            Your transfer was completed and verified on the Stellar network.
          </p>
        </div>
      </div>

      {/* POP Card */}
      <Card
        ref={popRef}
        className="overflow-hidden rounded-2xl border border-border bg-card shadow-xl shadow-background/50"
      >
        {/* Header with logo */}
        <div className="flex items-center justify-between border-b border-primary/20 bg-primary px-5 py-4">
          <div className="flex items-center gap-3">
            <Image
              src="/isotipo.png"
              alt="POP"
              width={28}
              height={28}
              className="rounded-md brightness-200"
            />
            <span className="text-lg font-bold text-primary-foreground">
              Proof of Payment
            </span>
          </div>
          <Badge className="border-primary-foreground/20 bg-primary-foreground/10 text-primary-foreground">
            <CheckCircle2 className="mr-1 h-3 w-3" />
            Verified
          </Badge>
        </div>

        {/* Body */}
        <div className="p-5">
          {/* Transfer summary */}
          <div className="mb-5 flex flex-col items-center gap-3 text-center">
            <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
              Transfer amount
            </p>
            <div className="flex items-center gap-5">
              <div>
                <p className="text-3xl font-bold text-foreground">
                  {pop.originAmount.toLocaleString()}
                </p>
                <p className="text-sm text-muted-foreground">
                  {pop.originCurrency}
                </p>
              </div>
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10">
                <ArrowRight className="h-5 w-5 text-primary" />
              </div>
              <div>
                <p className="text-3xl font-bold text-primary">
                  {pop.destinationAmount.toLocaleString()}
                </p>
                <p className="text-sm text-muted-foreground">
                  {pop.destinationCurrency}
                </p>
              </div>
            </div>
          </div>

          <Separator className="my-4" />

          {/* Details */}
          <div className="flex flex-col gap-3">
            <DetailRow label="Transaction ID" value={transaction.id}>
              <CopyButton
                text={transaction.id}
                label="txId"
                copied={copied}
                onCopy={copyToClipboard}
              />
            </DetailRow>
            <DetailRow
              label="Date"
              value={new Date(pop.timestamp).toLocaleString()}
            />
            <DetailRow label="Route" value={pop.route} />
            <DetailRow
              label="Exchange Rate"
              value={`1 ${pop.originCurrency} = ${pop.exchangeRate} ${pop.destinationCurrency}`}
            />
            <DetailRow
              label="Total Fees"
              value={`${pop.totalFees.toFixed(2)} ${pop.originCurrency}`}
            />

            <Separator className="my-2" />

            <div className="flex flex-col gap-1.5">
              <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
                Stellar Transaction
              </span>
              <div className="flex items-center gap-2">
                <code className="flex-1 break-all rounded-lg bg-muted px-3 py-2 font-mono text-xs text-foreground">
                  {pop.stellarTxHash}
                </code>
                <CopyButton
                  text={pop.stellarTxHash}
                  label="hash"
                  copied={copied}
                  onCopy={copyToClipboard}
                />
              </div>
              <a
                href={`https://stellar.expert/explorer/public/tx/${pop.stellarTxHash}`}
                target="_blank"
                rel="noopener noreferrer"
                className="mt-1 flex items-center gap-1 text-xs text-primary transition-colors hover:text-primary/80 hover:underline"
              >
                View on Stellar Explorer
                <ExternalLink className="h-3 w-3" />
              </a>
            </div>
          </div>
        </div>
      </Card>

      {/* Actions */}
      <div className="flex flex-col gap-3 sm:flex-row">
        <Button
          onClick={handleDownload}
          variant="outline"
          className={cn(
            "flex-1 gap-2 rounded-xl bg-transparent",
            "transition-all duration-200",
            "hover:scale-[1.02] hover:shadow-md",
            "active:scale-[0.98]"
          )}
        >
          <Download className="h-4 w-4" />
          Download Proof
        </Button>
        <Button
          onClick={() => {
            if (navigator.share) {
              navigator.share({
                title: "Proof of Payment - POP",
                text: `Transfer ${pop.originAmount} ${pop.originCurrency} to ${pop.destinationAmount} ${pop.destinationCurrency} verified. TX: ${transaction.id}`,
              });
            } else {
              copyToClipboard(
                `POP Proof of Payment: ${transaction.id} | ${pop.originAmount} ${pop.originCurrency} -> ${pop.destinationAmount} ${pop.destinationCurrency}`,
                "share"
              );
            }
          }}
          variant="outline"
          className={cn(
            "flex-1 gap-2 rounded-xl bg-transparent",
            "transition-all duration-200",
            "hover:scale-[1.02] hover:shadow-md",
            "active:scale-[0.98]"
          )}
        >
          <Share2 className="h-4 w-4" />
          {copied === "share" ? "Copied!" : "Share"}
        </Button>
        <Button
          onClick={onNewTransfer}
          className={cn(
            "flex-1 gap-2 rounded-xl bg-primary text-primary-foreground",
            "transition-all duration-200",
            "hover:scale-[1.02] hover:shadow-lg hover:shadow-primary/25",
            "active:scale-[0.98]"
          )}
        >
          New Transfer
        </Button>
      </div>
    </div>
  );
}

function DetailRow({
  label,
  value,
  children,
}: {
  label: string;
  value: string;
  children?: React.ReactNode;
}) {
  return (
    <div className="flex items-center justify-between gap-2">
      <span className="text-sm text-muted-foreground">{label}</span>
      <div className="flex items-center gap-1.5">
        <span className="text-right text-sm font-medium text-foreground">
          {value}
        </span>
        {children}
      </div>
    </div>
  );
}

function CopyButton({
  text,
  label,
  copied,
  onCopy,
}: {
  text: string;
  label: string;
  copied: string | null;
  onCopy: (text: string, label: string) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => onCopy(text, label)}
      className={cn(
        "rounded-md p-1.5 text-muted-foreground",
        "transition-all duration-150",
        "hover:bg-muted hover:text-foreground",
        "active:scale-90"
      )}
      aria-label={`Copy ${label}`}
    >
      {copied === label ? (
        <CheckCircle2 className="h-3.5 w-3.5 text-success" />
      ) : (
        <Copy className="h-3.5 w-3.5" />
      )}
    </button>
  );
}
